WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Bank: 3pn-???-mm=0.95-eta_star=???-n_eff=???
	p = 0.0021000000000000003 +/- 0.0003236966172205077
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Bank: 3pn-???-mm=0.9-eta_star=???-n_eff=???
	p = 0.004 +/- 0.00044631827208842803
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Bank: 3pn-???-mm=0.85-eta_star=???-n_eff=???
	p = 0.0058000000000000005 +/- 0.0005369525118667383
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Bank: 3pn-???-mm=0.8-eta_star=???-n_eff=???
	p = 0.010150000000000001 +/- 0.0007087657405659504
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Bank: 3pn-???-mm=0.75-eta_star=???-n_eff=???
	p = 0.00995 +/- 0.0007018189759475014
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Bank: 3pn-???-mm=0.95-eta_star=???-n_eff=???
	p = 0.0022500000000000003 +/- 0.0003350326476628807
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Bank: 3pn-???-mm=0.9-eta_star=???-n_eff=???
	p = 0.004 +/- 0.000446318272088428
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Bank: 3pn-???-mm=0.85-eta_star=???-n_eff=???
	p = 0.00585 +/- 0.0005392484353245727
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Bank: 3pn-???-mm=0.8-eta_star=???-n_eff=???
	p = 0.01025 +/- 0.000712212661358951
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Bank: 3pn-???-mm=0.75-eta_star=???-n_eff=???
	p = 0.01 +/- 0.0007035623639735144
2021-11-12 20:23:42.309910: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/nvvm/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/extras/CUPTI/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/binutils/2.32-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/zlib/1.2.11-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib
2021-11-12 20:23:42.763700: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/nvvm/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/extras/CUPTI/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/binutils/2.32-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/zlib/1.2.11-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib
2021-11-12 20:23:42.773630: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/nvvm/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/extras/CUPTI/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/binutils/2.32-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/zlib/1.2.11-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib
2021-11-12 20:23:43.660118: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/nvvm/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/extras/CUPTI/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/binutils/2.32-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/zlib/1.2.11-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib
2021-11-12 20:23:43.660181: W external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Bank: 3pn-???-mm=0.95-eta_star=???-n_eff=???
	p = 0.0022500000000000003 +/- 0.0003350326476628807
2021-11-12 20:27:03.750084: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/nvvm/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/extras/CUPTI/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/binutils/2.32-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/zlib/1.2.11-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib
2021-11-12 20:27:04.045327: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/nvvm/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/extras/CUPTI/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/binutils/2.32-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/zlib/1.2.11-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib
2021-11-12 20:27:04.051273: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/nvvm/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/extras/CUPTI/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/binutils/2.32-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/zlib/1.2.11-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib
2021-11-12 20:27:04.764276: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/nvvm/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/extras/CUPTI/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/binutils/2.32-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/zlib/1.2.11-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib
2021-11-12 20:27:04.764348: W external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
2021-11-12 20:29:33.418964: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/nvvm/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/extras/CUPTI/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/binutils/2.32-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/zlib/1.2.11-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib
2021-11-12 20:29:33.419236: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/nvvm/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/extras/CUPTI/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/binutils/2.32-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/zlib/1.2.11-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib
2021-11-12 20:29:33.419237: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/nvvm/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/extras/CUPTI/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/binutils/2.32-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/zlib/1.2.11-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib
2021-11-12 20:29:33.419241: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/nvvm/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/extras/CUPTI/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/binutils/2.32-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/zlib/1.2.11-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib
2021-11-12 20:29:33.419236: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/nvvm/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/extras/CUPTI/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/binutils/2.32-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/zlib/1.2.11-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib
2021-11-12 20:29:33.942847: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/nvvm/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/extras/CUPTI/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/binutils/2.32-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/zlib/1.2.11-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib
2021-11-12 20:29:33.945785: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/nvvm/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/extras/CUPTI/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/binutils/2.32-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/zlib/1.2.11-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib
2021-11-12 20:29:33.952481: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/nvvm/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/extras/CUPTI/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/binutils/2.32-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/zlib/1.2.11-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib
2021-11-12 20:29:33.953412: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/nvvm/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/extras/CUPTI/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/binutils/2.32-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/zlib/1.2.11-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib
2021-11-12 20:29:33.954139: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/nvvm/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/extras/CUPTI/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/binutils/2.32-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/zlib/1.2.11-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib
2021-11-12 20:29:33.963211: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/nvvm/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/extras/CUPTI/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/binutils/2.32-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/zlib/1.2.11-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib
2021-11-12 20:29:33.981158: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/nvvm/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/extras/CUPTI/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/binutils/2.32-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/zlib/1.2.11-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib
2021-11-12 20:29:33.984069: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/nvvm/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/extras/CUPTI/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/binutils/2.32-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/zlib/1.2.11-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib
2021-11-12 20:29:33.986618: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/nvvm/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/extras/CUPTI/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/binutils/2.32-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/zlib/1.2.11-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib
2021-11-12 20:29:33.989474: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/nvvm/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/extras/CUPTI/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/binutils/2.32-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/zlib/1.2.11-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib
2021-11-12 20:29:34.826944: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/nvvm/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/extras/CUPTI/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/binutils/2.32-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/zlib/1.2.11-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib
2021-11-12 20:29:34.826981: W external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2021-11-12 20:29:34.827019: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/nvvm/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/extras/CUPTI/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/binutils/2.32-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/zlib/1.2.11-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib
2021-11-12 20:29:34.827047: W external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2021-11-12 20:29:34.827109: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/nvvm/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/extras/CUPTI/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/binutils/2.32-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/zlib/1.2.11-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib
2021-11-12 20:29:34.827170: W external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2021-11-12 20:29:34.827107: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/nvvm/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/extras/CUPTI/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/binutils/2.32-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/zlib/1.2.11-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib
2021-11-12 20:29:34.827168: W external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2021-11-12 20:29:34.827211: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/nvvm/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/extras/CUPTI/lib64:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243-GCC-8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/binutils/2.32-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/zlib/1.2.11-GCCcore-8.3.0/lib:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib64:/sw/arch/Debian10/EB_production/2019/software/GCCcore/8.3.0/lib
2021-11-12 20:29:34.827236: W external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Bank: 3pn-???-mm=0.8-eta_star=???-n_eff=???
	p = 0.01025 +/- 0.000712212661358951
Bank: 3pn-???-mm=0.9-eta_star=???-n_eff=???
	p = 0.004 +/- 0.000446318272088428
Bank: 3pn-???-mm=0.85-eta_star=???-n_eff=???
	p = 0.00585 +/- 0.0005392484353245727
Bank: 3pn-???-mm=0.75-eta_star=???-n_eff=???
	p = 0.01 +/- 0.0007035623639735144
Bank: 3pn-???-mm=0.95-eta_star=???-n_eff=???
	p = 0.0022500000000000003 +/- 0.0003350326476628807
